#!/usr/bin/env bash
# Step 4 of docs/DEPLOY.md — put nginx in front of the container.
#
#   sudo ./cli/nginx.sh tabletab.co
#
# Reads APP_PORT from .env, renders cli/nginx/default.conf.template,
# installs it, validates the config, and reloads nginx. Safe to re-run.
set -euo pipefail

DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
  echo "usage: sudo $0 <domain>   e.g. sudo ./cli/nginx.sh tabletab.co" >&2
  exit 1
fi
[ "$(id -u)" -eq 0 ] || { echo "run with sudo" >&2; exit 1; }

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATE="$ROOT/cli/nginx/default.conf.template"
[ -f "$TEMPLATE" ] || { echo "missing $TEMPLATE" >&2; exit 1; }

# --- port ---------------------------------------------------------------
APP_PORT=3000
if [ -f "$ROOT/.env" ]; then
  # shellcheck disable=SC2046
  APP_PORT="$(grep -E '^APP_PORT=' "$ROOT/.env" | tail -1 | cut -d= -f2 | tr -d '[:space:]')"
  APP_PORT="${APP_PORT:-3000}"
else
  echo "!! no .env found — assuming APP_PORT=$APP_PORT"
fi
echo "==> domain=$DOMAIN  APP_PORT=$APP_PORT"

# --- is the container actually up? --------------------------------------
if ! curl -fsS -m 5 "http://127.0.0.1:$APP_PORT" >/dev/null 2>&1; then
  echo "!! nothing answering on 127.0.0.1:$APP_PORT"
  echo "   start it first:  ./cli/docker.sh prod-up     (then re-run this script)"
  exit 1
fi
echo "==> container is answering on $APP_PORT"

# --- nginx --------------------------------------------------------------
if ! command -v nginx >/dev/null; then
  echo "==> installing nginx"
  apt-get update -qq && apt-get install -y -qq nginx
fi

# Debian/Ubuntu layout uses sites-available; others use conf.d.
if [ -d /etc/nginx/sites-available ]; then
  TARGET="/etc/nginx/sites-available/$DOMAIN"
  LINK="/etc/nginx/sites-enabled/$DOMAIN"
else
  TARGET="/etc/nginx/conf.d/$DOMAIN.conf"
  LINK=""
fi

sed -e "s/__DOMAIN__/$DOMAIN/g" -e "s/__APP_PORT__/$APP_PORT/g" "$TEMPLATE" > "$TARGET"

# Hosts with IPv6 disabled cannot bind [::]:80 — nginx -t hard-fails there.
if [ ! -f /proc/net/if_inet6 ]; then
  sed -i 's/^\( *\)listen \[::\]:80;/\1# listen [::]:80;   # disabled: no IPv6 on this host/' "$TARGET"
  echo "==> no IPv6 on this host — commented out the [::]:80 listener"
fi

[ -n "$LINK" ] && ln -sfn "$TARGET" "$LINK"
echo "==> wrote $TARGET"

# The default site also claims port 80 and can shadow this one.
if [ -L /etc/nginx/sites-enabled/default ]; then
  rm -f /etc/nginx/sites-enabled/default
  echo "==> removed the default site (it was claiming port 80)"
fi

# --- real client IPs from Cloudflare ------------------------------------
# Build in a temp file first: a failed fetch must not clobber a good config with
# an empty one (that would silently make every visitor look like a Cloudflare IP).
REALIP=/etc/nginx/conf.d/cloudflare-realip.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "==> refreshing Cloudflare IP ranges for real_ip"
V4="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4 || true)"
V6="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v6 || true)"

if [ -n "$V4" ]; then
  {
    echo "# Generated by cli/nginx.sh — re-run occasionally to refresh."
    for cidr in $V4 $V6; do echo "set_real_ip_from $cidr;"; done
    echo "real_ip_header CF-Connecting-IP;"
  } > "$TMP"
  install -m 644 "$TMP" "$REALIP"
  echo "==> wrote $REALIP ($(grep -c set_real_ip_from "$REALIP") ranges)"
elif [ -f "$REALIP" ]; then
  echo "!! could not fetch Cloudflare ranges — keeping the existing $REALIP"
else
  echo "!! could not fetch Cloudflare ranges and none are installed."
  echo "   Logs will show Cloudflare edge IPs instead of real visitors."
  echo "   Re-run this script once the box has outbound network access."
fi

nginx -t

# systemd on a normal VPS; the fallback covers containers and minimal images.
if command -v systemctl >/dev/null 2>&1 && systemctl list-units >/dev/null 2>&1; then
  systemctl enable --now nginx >/dev/null 2>&1 || true
  systemctl reload nginx || systemctl restart nginx
else
  # No systemd: reload if it is already running, otherwise start it.
  nginx -s reload 2>/dev/null || nginx
fi

# Prove it: something must actually be listening on 80 now.
sleep 1
if curl -fsS -m 5 -o /dev/null -H "Host: $DOMAIN" http://127.0.0.1/; then
  echo "==> nginx is serving $DOMAIN on :80"
else
  echo "!! nginx did not answer on :80 — check: nginx -t && journalctl -u nginx -n 30" >&2
  exit 1
fi

echo
echo "==> done. Verify from this box:"
echo "     curl -I -H 'Host: $DOMAIN' http://127.0.0.1"
echo
echo "In Cloudflare, set SSL/TLS -> Overview -> encryption mode to *Flexible*"
echo "(this server listens on :80 only). See docs/DEPLOY.md to move to Full (strict)."
